[package]
name = "kaitai"
version = "0.2.0"
authors = ["Bradlee Speice <bradlee@speice.io>", "Aon"]
edition = "2021"
rust-version = "1.63"

[features]
type_name_of_val = []

[dependencies]
encoding-next = "0.3"
cp437 = "0.1"
unicode-segmentation = "1"
flate2 = "1"

[dev-dependencies]
tempfile = "3"
